swagger: '2.0'
info:
  description: Metadata Query for LAAWS
  version: 1.0.0
  title: LAAWS-Metadata Query
  contact:
    name: 'LOCKSS Support'
    url: 'http://www.lockss.org/'
    email: 'support@lockss.org'
  license:
    name: 'Modified BSD License'
    url: 'http://www.lockss.org/support/open-source-license/'
host: 'laaws.lockss.org:443'
basePath: /mdq
tags:
  - name: Default
    description: Default section
  - name: url
    description: Tasks that return URLs.
schemes:
  - https
paths:
  /url/openurl:
    post:
      tags:
        - url
      summary: Performs an OpenURL query.
      description: Provides the URL that results from performing an OpenURL query.
      operationId: postOpenUrl
      consumes: []
      produces:
        - application/json
      parameters:
        - name: params
          in: body
          description: The OpenURL parameters.
          required: true
          schema:
            $ref: '#/definitions/openUrlParams'
      responses:
        '200':
          description: The data related to the performed OpenURL query.
          schema:
            $ref: '#/definitions/urlInfo'
  '/url/doi/{doi}':
    get:
      tags:
        - url
      summary: Gets the URL for a DOI.
      description: Provides the access URL for a DOI given the DOI.
      operationId: getUrlDoi
      consumes: []
      produces:
        - application/json
      parameters:
        - name: doi
          in: path
          description: The DOI for which the access URL is requested.
          required: true
          type: string
      responses:
        '200':
          description: The access URL for the specified DOI.
          schema:
            $ref: '#/definitions/urlInfo'
definitions:
  openUrlParams:
    type: object
    description: The map of OpenURL query parameters.
    additionalProperties:
      type: string
      description: The value of the parameter for the parameter name.
  urlInfo:
    type: object
    required:
      - params
      - url
    properties:
      params:
        type: object
        description: The map of parameters.
        additionalProperties:
          type: string
          description: The value of the parameter for the parameter name.
      url:
        type: string
        description: The URL.
    description: The information related to a URL.
